import{a as b,i as f,S as L}from"./assets/vendor-DtRopbQG.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&a(d)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();const w="49358798-a0fde913d86352b572e9384bf",v="https://pixabay.com/api/";async function h(r,e=1){try{const o=await b.get(v,{params:{key:w,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:e}});if(!o.data.hits.length)throw new Error("Sorry, there are no images matching your search query. Please try again!");return o.data}catch(o){return f.error({message:`${o.message}`,messageColor:"white",position:"topRight",color:"#ef4040"}),{hits:[],totalHits:0}}}function g(r){return r.map(e=>`<li class="gallery-item">
    <a class="gallery-link" href="${e.largeImageURL}">
    <img
    class="gallery-image"
    src="${e.webformatURL}"
    alt="${e.tags.slice(0,120)}"
    />
    </a>
    <div class="item-subtitle">
    <p class="item-text"><b>Likes</b> ${e.likes}</p>
    <p class="item-text"><b>Views</b> ${e.views}</p>
    <p class="item-text"><b>Comments</b> ${e.comments}</p>
    <p class="item-text"><b>Downloads</b> ${e.downloads}</p>
    </div>
    </li>`).join("")}let p=new L(".gallery a",{captionsData:"alt",captionDelay:250}),n="",y="",i=1,u=1;const S=document.querySelector(".form"),q=document.querySelector("input"),m=document.querySelector(".gallery"),l=document.querySelector(".loader"),c=document.querySelector(".btn");S.addEventListener("submit",$);q.addEventListener("input",E);c.addEventListener("click",x);function E(r){n=r.target.value.trim()}async function $(r){r.preventDefault();const e=r.currentTarget;if(c.classList.add("hidden"),i=1,n===""){f.error({message:"Fill in the search field!",messageColor:"white",position:"topRight",color:"#ef4040"}),e.reset();return}y=n,m.innerHTML="",l.classList.remove("hidden");try{const{hits:o,totalHits:a}=await h(n,i);if(a===0)return;u=Math.ceil(a/15),m.insertAdjacentHTML("beforeend",g(o)),p.refresh(),i<u&&c.classList.remove("hidden")}catch(o){console.error("Error:",o)}finally{l.classList.add("hidden")}e.reset(),n=""}async function x(){i+=1,l.classList.remove("hidden");try{const{hits:r}=await h(y,i);m.insertAdjacentHTML("beforeend",g(r)),p.refresh();const e=document.querySelector(".gallery-item");if(e){const o=e.getBoundingClientRect().height*2;window.scrollBy({top:o,behavior:"smooth"})}i===u&&(f.error({position:"topRight",message:"We're sorry, but you've reached the end of search results.",messageColor:"white",color:"#ef4040"}),c.classList.add("hidden"))}catch(r){console.log(r)}finally{l.classList.add("hidden")}}
//# sourceMappingURL=index.js.map
